version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Generate idp.xml
          command: |
            cp idp.xml.template app/src/main/res/values/idp.xml
            sed -i "s/stage-id.valtech.com/id.valtech.com/g" app/src/main/res/values/idp.xml
            sed -i "s/CLIENT_SECRET_HERE/$IDP_CLIENT_SECRET/g" app/src/main/res/values/idp.xml
      - run:
          name: Run Tests
          #command: ./gradlew lint test # TODO: Enable linting
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Assemble app (debug)
          command: ./gradlew assembleDebug
      - run: # TODO: Only build release apk on master branch
          name: Assemble app (release)
          command: |
            echo $VALTECH_KEYSTORE | base64 --decode > valtech.keystore
            ./gradlew assembleRelease
            rm valtech.keystore
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
